class Hello:
    def __init__(self, name: str) -> None: ...
    def greet(self) -> str: ...

# python의 유연성이 제한 type 확인을 잘 해야함
# add는 cpp_hello.cpp의 add와 연결

def add(left: int, right: int) -> int: ...
